version: '3.9'

services:

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:7.0-ubuntu-latest
    container_name: zabbix-server
    environment:
      - TZ=America/Sao_Paulo
      - DB_SERVER_HOST=zabbix-postgres
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
      - POSTGRES_DB=zabbix
    ports:
      - "10051:10051"
    depends_on:
      - zabbix-postgres
    networks:
      - monitoring

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-7.0-latest
    container_name: zabbix-web
    environment:
      - TZ=America/Sao_Paulo
      - PHP_TZ=America/Sao_Paulo    
      - ZBX_SERVER_HOST=zabbix-server
      - DB_SERVER_HOST=zabbix-postgres
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
    ports:
      - "8082:8080"
    depends_on:
      - zabbix-server
    networks:
      - monitoring

  zabbix-postgres:
    image: postgres:16
    container_name: zabbix-postgres
    environment:
      - TZ=America/Sao_Paulo
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
      - POSTGRES_DB=zabbix
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "4000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - zabbix-server
    networks:
      - monitoring
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
      - TZ=America/Sao_Paulo

  toolbox:
    image: curlimages/curl
    command: sleep infinity
    networks:
      - monitoring

networks:
  monitoring:
    name: monitoring